### ISSUE TITLE
"Cannot run program "npx" (in directory "")" Error while running jmeter Playwright  sampler 

### ISSUE THREAD

**Issue by rahul84gupta** [tonybaloney/jmeter-playwright#10]
Jmeter Version: 5.4
Playwright Jmeter version: 0.4.2

Steps:
1- Added latest Playwright Jmeter jar in Jmeter project folder inside "lib/ext" folder.
2- Installed Node js (v18.15.0)
3- Created Playwright test suite
4- Added new Playwright sampler in Jmx
5- Added the Playwright project folder path in Playwright sampler under "Test Directory" section.
![Sampler](https://github.com/tonybaloney/jmeter-playwright/assets/16269485/c0f7bc75-7977-4010-bfa5-dd982272b0b1)

6- Keep default "Playwright config" section.

**Getting below Error on running the Jmeter Playwright Sampler.**

**Error:**
Launching npx playwright test --reporter junit --workers=2 --timeout=0 --project Signing Room in directory .
2023-07-14 16:05:58,204 ERROR o.a.j.t.ThreadGroup: Cannot run program "npx" (in directory ""): CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
2023-07-14 16:05:58,205 ERROR o.a.j.t.ThreadGroup: java.io.IOException: Cannot run program "npx" (in directory ""): CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at com.microsoft.playwright.jmeter.samplers.PlaywrightTestSampler.runNpxPlaywrightTest(PlaywrightTestSampler.kt:154)
	at com.microsoft.playwright.jmeter.samplers.PlaywrightTestSampler.sample(PlaywrightTestSampler.kt:91)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 9 more

2023-07-14 16:05:58,206 INFO o.a.j.t.JMeterThread: Thread finished: Play 1-1
2023-07-14 16:05:58,206 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[Play 1-1,6,main]
java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:176) ~[jmeter-playwright-0.4.2.jar:?]
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:145) ~[jmeter-playwright-0.4.2.jar:?]
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:127) ~[jmeter-playwright-0.4.2.jar:?]
	at com.microsoft.playwright.jmeter.junit.JUnitDeserializer.<init>(JUnitDeserializer.kt:5) ~[jmeter-playwright-0.4.2.jar:?]
	at com.microsoft.playwright.jmeter.samplers.PlaywrightTestSampler.sample(PlaywrightTestSampler.kt:98) ~[jmeter-playwright-0.4.2.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) ~[ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_371]
2023-07-14 16:05:58,209 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test

**Playwright Test suite- POM.xml File:**

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>esignLoadTest22</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.31.0</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.playwright.jmeter</groupId>
            <artifactId>jmeter-playwright</artifactId>
            <version>0.4.2</version>
        </dependency>

        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.1.2</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.7</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.7</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>`

**Comment by tonybaloney** [comment]
This suggests that npx is not available in $PATH

If you start a command line session and type "npx" does it run?

**Comment by KevBat** [comment]
New to jmeter and playwright - I am also encountering the same issue. I can confirm that npx is in my $PATH variable.

My steps are very simple:

1. I created a new test plan in Jmeter 5.6.2
2. Created a new "Playwright Thread Group"
3. Created a new "Playwright Test Sampler" and specified my Playwright test directory with the .ts file and specified the Playwright config.ts file
4. Hit "Start" button

![image](https://github.com/tonybaloney/jmeter-playwright/assets/9285242/230c4bd2-4b30-4d99-8206-44fbcf20663e)

**Comment by tonybaloney** [comment]
When it spawns npx it uses the PATH environment variable that JMeter was started under. I think it's not inheriting the user PATH variable correctly. I can either add an option to set the PATH variable, or find another mechanism to locate npx.

Please bear with me

**Comment by mramos-planit** [comment]
hi Tony. Is there any timeline when you're planning to merge the fix?

**Comment by danielsan281281** [comment]
Same error. npx is in my PATH.

2024-05-05 18:25:48,226 INFO o.a.j.t.ThreadGroup: Launching npx playwright test --reporter junit --workers=1 --repeat-each=1 --timeout=0 in directory .
2024-05-05 18:25:48,227 ERROR o.a.j.t.ThreadGroup: Cannot run program "npx" (in directory ""): CreateProcess error=123,

**Comment by mgev-d** [comment]
Hello Tony,

we do expierence the same issue. See our findings here below and tried different MS OS versions, JDK versions and JMeter versions, like JMeter 5.1.1, 5.5 and 5.6.2 giving all the same result and also the different JMeter GUI modes.

Running a test using the JMeter GUI then this is the response.

**Same Error message and the .npx is in my PATH. Neither user PATH nor System PATH work.**
Here is the output of JMeter: 
[JMeter-NMP error.txt](https://github.com/user-attachments/files/16929325/JMeter-NMP.error.txt)

1. Path

> C:\PW\playwright-for-loadtesting\tests>echo %path%
> C:\Python312\Scripts\;C:\Python312\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\java\jdk-17.0.0.1\bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Roaming\npm
> 

> 

Running npx as you suggeted:

> C:\>npx
> 
> Entering npm script environment at location:
> C:\
> Type 'exit' or ^D when finished
> 
> Microsoft Windows [Version 10.0.22000.3147]
> (c) Microsoft Corporation. All rights reserved.
> 

2. Variable testdirectory and configfile in JMX file are empty

Noticed that in the JMeter Testplan.jmx , the data (location of the testdirectory and configfile) are empty. It is even errased when manualy added in the .JMX file upon saving or running a JMeter test.

>  <com.microsoft.playwright.jmeter.samplers.PlaywrightTestSampler guiclass="com.microsoft.playwright.jmeter.samplers.PlaywrightTestSamplerGUI" testclass="com.microsoft.playwright.jmeter.samplers.PlaywrightTestSampler" testname="Playwright Test Sampler" enabled="true">

         **<stringProp name="Playwright.testDirectory"></stringProp>
          <stringProp name="Playwright.configFile"></stringProp>**
          <intProp name="Playwright.workerCount">10</intProp>
          <intProp name="Playwright.timeout">0</intProp>
          <intProp name="Playwright.repeatEach">7</intProp>
          <stringProp name="Playwright.extraOptions">CLI options</stringProp>
          <stringProp name="Playwright.grep">filter</stringProp>
          <stringProp name="Playwright.grepInvert">invert test filer</stringProp>
          <stringProp name="Playwright.project">PW-test</stringProp>
        </com.microsoft.playwright.jmeter.samplers.PlaywrightTestSampler>

> 

3. Running JMeter in CLI mode 
Here below the output when running JMeter in CLI mode with the manuly added file´-paths: 

>C:\apache-jmeter-5.5\bin>jmeter -n -t c:\PW\Playwright_Test_Sampler-v3.jmx

> Creating summariser <summary>
> <Created` the tree successfully using c:\PW\Playwright_Test_Sampler-v3.jmx
> Starting standalone test @ 2024 Sep 9 12:25:15 CEST (1725877515804)
> Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
> summary =      0 in 00:00:00 = /s Avg:     0 Min: 9223372036854775807 Max: -9223372036854775808 Err:     0 (0,00%)
> Tidying up ...    @ 2024 Sep 9 12:25:16 CEST (1725877516024)
> ... end of run
> >>>

Looking forward seeing your advice.
Kind Regards
mg

**Comment by smkurita** [comment]
Hello Tony and other thread participants.

We are trying to run jmeter-playwright in a pure Linux/Ubuntu system and we find the same problem.
npx is in our PATH and have been installed systemwide , npx is in /usr/bin/npx but Jmeter fails to find npx and we got the same error:
ERROR o.a.j.t.ThreadGroup: Cannot run program "npx" (in directory ""): error=2, No such file or directory

We would love any suggestion to be able to pass the correct PATH to JMeter.

Thanks for work in this nice plugin ! 

Santi from Kurita.

**Comment by smkurita** [comment]
> hi Tony. Is there any timeline when you're planning to merge the fix?

Did the FIX came ever ?
