### ISSUE TITLE
Unable to Add Sampler

### ISSUE THREAD

**Issue by suhas296** [tonybaloney/jmeter-playwright#8]
Hi,

I get the below error when i try to add the sampler.

ERROR o.a.j.g.a.AddToTree: Exception while adding a component to tree.
java.lang.NullPointerException: testDirectory.selectedFile must not be null
	at com.microsoft.playwright.jmeter.samplers.PlaywrightTestSamplerGUI.modifyTestElement(PlaywrightTestSamplerGUI.kt:151) ~[jmeter-playwright-0.4.0-20230609.044954-1.jar:?]
	at com.microsoft.playwright.jmeter.samplers.PlaywrightTestSamplerGUI.createTestElement(PlaywrightTestSamplerGUI.kt:142) ~[jmeter-playwright-0.4.0-20230609.044954-1.jar:?]
	at org.apache.jmeter.gui.GuiPackage.createTestElement(GuiPackage.java:373) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.AddToTree.doAction(AddToTree.java:67) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.5]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_202]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_202]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_202]
	at java.awt.EventDispatchThread.run(Unknown Source) ~[?:1.8.0_202]
2023-07-04 12:16:15,477 ERROR o.a.j.u.JMeterUtils: testDirectory.selectedFile must not be null

**Comment by tonybaloney** [comment]
Thanks for the report, what version of JMeter are you using? I'll release a patch to fix this bug

**Comment by tonybaloney** [comment]
Please download and use the JAR from the latest release https://github.com/tonybaloney/jmeter-playwright/releases/tag/0.4.2
